services:
  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--enable-feature=remote-write-receiver' # Bắt buộc để k6 đẩy dữ liệu vào

    ports:
      - '9090:9090'
    extra_hosts:
      - 'host.docker.internal:host-gateway' # Thêm dòng này để Prometheus có thể truy cập NestJS chạy trên máy host

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Mật khẩu đăng nhập Grafana
    depends_on:
      - prometheus
