@root=http://localhost:3000/api/v1

### Create location region
POST {{root}}/location-regions
content-type: application/json

{
    "name": "District 1",
    "type": "district",
    "parent": "a362ec31-bda6-4917-9916-4efc4ca4bc64"
}

### Get all location regions
GET {{root}}/location-regions?page=1&limit=10
content-type: application/json

### Get a location region by id
GET {{root}}/location-regions/a03b220c-1941-4000-9694-24d3c1155716
content-type: application/json

### Update a location region by id
PATCH {{root}}/location-regions/a03b220c-1941-4000-9694-24d3c1155716
content-type: application/json

{
    "name": "District 2"
}

### Delete a location region by id
DELETE {{root}}/location-regions/a362ec31-bda6-4917-9916-4efc4ca4bc64
content-type: application/json
