@root=http://localhost:3000/api/v1

### Create stores
POST {{root}}/stores
content-type: application/json

{
    "locationRegion": "a03b220c-1941-4000-9694-24d3c1155716",
    "name": "Store 1",
    "address": "123 Main St",
    "openingHours": "08:00",
    "closingHours": "22:00",
    "lat": 10.775,
    "lng": 106.7,
    "isActive": true,
    "phone": [
        {
            "name": "Main Phone",
            "phone": "0123456789"
        }
    ]
}

### Get all stores
GET {{root}}/stores?page=1&limit=10
content-type: application/json

### Get a store by id
GET {{root}}/stores/a03b220c-1941-4000-9694-24d3c1155716
content-type: application/json

### Update a store by id
PATCH {{root}}/stores/a03b220c-1941-4000-9694-24d3c1155716
content-type: application/json

{
    "name": "Store 2",
    "address": "456 Main St",
}

### Delete a store by id
DELETE {{root}}/stores/a03b220c-1941-4000-9694-24d3c1155716
content-type: application/json
