@url=http://localhost:9000/api/user
@accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjkzNGVhOWNjLWIxODQtNGE4NS1iYTUxLTQzMTRjN2I5MTRkMSIsImRldmljZUluZm8iOiJ2c2NvZGUtcmVzdGNsaWVudCIsImlhdCI6MTc2NTU1NjM1MiwiZXhwIjoxNzY1NTU5OTUyfQ.QusIuq0jy9XkxTjDL9bCGoYiw6nYSRYAldIKcB-OLr8

###
POST {{url}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
    "email": "buithanhliem2@gmail.com",  
    "phone": "0375255072",  
    "password": "liemdev123",  
    "username": "liemdev2",
    "roleIds": ["d25a0b68-04a7-4ebd-bae2-c8d843b3251c", "7b3b8e11-0680-4aa3-8431-95fe655448a6"]
}

###
GET {{url}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}
